# Generated by Django 5.2.4 on 2026-03-16 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=256)),
                ('algorithm_name', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('usage_timestamp', models.DateTimeField(auto_now_add=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
